### ISSUE TITLE
Do you know when Presence will be supported?

### ISSUE THREAD

**Issue by tenaz3** [braverhealth/phoenix-socket-dart#1]

**Comment by matehat** [comment]
Hello! Thanks for the issue #1 ! 😄 

I just hadn't had a personal need for it yet, if there's interest from the community, I'd try to squeeze some time to make it work!

**Comment by papakay** [comment]
Hello @matehat I really like to commend the great work you did on this library. Please I'm also interested in the Presence feature.

Thanks.

**Comment by tenaz3** [comment]
Indeed was a really good work. I used other lib, now I will change to this one for sure!  I also will be willing to help if it's needed. Just let me know

**Comment by aguilaair** [comment]
Would be awsome to see presence supported 👍

**Comment by matehat** [comment]
Thanks for the input, that helps me judge the priority of things 😄 

Also, PRs are always welcome!

**Comment by ol88** [comment]
Hi, I just submitted a PR to make presence work at a basic level #11 

Since I'm not particularly experienced. not doubt someone needs to have a look and review/test carefully but it works for what I need at least.

**Comment by matehat** [comment]
Awesome thanks @ol88 ! I'll have a look asap

**Comment by ol88** [comment]
Thanks for the merging this @matehat!

Now that Presence support has been merged into master, I would encourage anyone to give it a go and test/improve as needed.

You can look at the example app under example/flutter_presence_app to get started. (It requires a Phoenix server setup for presence as per https://hexdocs.pm/phoenix/presence.html#content to work).

I believe this issue can be closed and bugs/improvement be reported separately in their own new issue.
