### ISSUE TITLE
0.4.7 hotfix!

### ISSUE THREAD

**Issue by carlosmobile** [braverhealth/phoenix-socket-dart#14]
We need hotfix in 0.4.7.

Channel.dart need to change line 52

  /// Parameters passed to the backend at join time.
  final Map<String, String> parameters;

to:

 final Map<String, dynamic> parameters;

Thanks!!

**Comment by matehat** [comment]
@carlosmobile oh no! do you have time to push this fix?

**Comment by carlosmobile** [comment]
Yes, fixed!
