### ISSUE TITLE
More complex examples

### ISSUE THREAD

**Issue by agramichael** [braverhealth/phoenix-socket-dart#2]
Hey, would it be possible to get some more complex examples for learning?

Something doing everything async: connecting to a socket, connecting to a channel, receiving broadcasts, pushing events and receiving their responses, all with futures so the UI is updated once the response is received?

**Comment by matehat** [comment]
Great idea, I'll try to come up with something quickly

**Comment by TylerSustare** [comment]
This would be great! Even one example on how to use the counter app to just push and receive phoenix updates instead of using state would be appreciated.
