### ISSUE TITLE
Sound null-safety

### ISSUE THREAD

**Issue by aguilaair** [braverhealth/phoenix-socket-dart#23]
Hey!

It'd be awesome to support sound null safety, now that it's on stable (Flutter 2.0.0)

**Comment by aguilaair** [comment]
I can try working on a PR to use as a starting point if I have time but I'd love to have some help on reviewing it

**Comment by matehat** [comment]
Yes! that'd be awesome, we're also internally getting on the null-safety bandwagon, at last. If you want to take a stab at it, please do! I'll be happy to review. Otherwise, I should get to it this week.
