### ISSUE TITLE
How to check event name from incoming Message ?

### ISSUE THREAD

**Issue by freewebwithme** [braverhealth/phoenix-socket-dart#27]
How can I check event name from Channel.messages?
`Message` has `event` property but can't do something like this
```
if(message.event == "new_order")
```

**Comment by matehat** [comment]
You can do:

```
if (message.event.value == 'foo') {

}
```

**Comment by freewebwithme** [comment]
oh nice! Thank you!

**Comment by matehat** [comment]
No problem! If you have more questions, feel free to ask them through the [discussion section](https://github.com/braverhealth/phoenix-socket-dart/discussions)!
