### ISSUE TITLE
No errors if connection fails

### ISSUE THREAD

**Issue by MapperMalte** [braverhealth/phoenix-socket-dart#41]
If there can't be a connection established, then no errors are thrown. It just doesn't work. This is really bad practice. You only eventually notice that you have "NULL" as your channel. Please throw an error if connection can not be established.

**Comment by matehat** [comment]
The socket will keep on trying for some time, so if you want to detect errors as soon as they happen, listen on the `PhoenixSocket.errorStream`.

**Comment by matehat** [comment]
Using a stream like `errorStream` is better than just throwing on `socket.connect()` because socket health is not a one-off thing. Connection can be dropped at any time _after_ the initial connection, and initial failure can be transient.
