### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MapperMalte** [braverhealth/phoenix-socket-dart#58]
Hey, thanks for the package.

I found this in your code:

```
Map<String, PhoenixChannel> channels = {};

   if (channels.isNotEmpty) {
      final foundChannels =
          channels.entries.where((element) => element.value.topic == topic);
      channel = foundChannels.isNotEmpty ? foundChannels.first.value : null;
    }
```

That has O(n) complexity for adding another channel.

What would you think about sth like this:

```
Map<String, PhoenixChannel> channels = {};
Map<String, PhoenixChannel> channelsByTopic = {};

PhoenixChannel? channel = channelsByTopic[topic];
```

reducing it to O(log n) complexity

**Comment by itxtoledo** [comment]
It looks like this package has been abandoned

**Comment by Pacane** [comment]
We're still using it daily internally. We'd be happy to take pull requests and review them!
