### ISSUE TITLE
proper way to set up headers

### ISSUE THREAD

**Issue by yuhao-nyc** [braverhealth/phoenix-socket-dart#88]
using this suggestion below didn't work:
```
return PhoenixSocket(
     "ws://localhost:4000/socket",
      webSocketChannelFactory: (uri) {
        return IOWebSocketChannel.connect(uri, headers: { "token": "My Token"});
      },
    );
```
is there any other way of setting headers?

**Comment by matehat** [comment]
Are you really looking for headers or for [Phoenix Socket params](https://hexdocs.pm/phoenix/Phoenix.Socket.html#c:connect/3-socket-params-and-assigns)?

**Comment by matehat** [comment]
To provide params, you'd do something like:

```dart
final socket = PhoenixSocker(
  url, 
  socketOptions: PhoenixSocketOptions(
    params: {
      'token': 'My Token',
    },
  ),
);
```

**Comment by yuhao-nyc** [comment]
> provide headers

yes I'm looking for a way to provide headers for the socket options

**Comment by matehat** [comment]
The WebSocket standard does not support setting custom headers on the WebSocket handshake process. The Phoenix-recommended way to provide client contextual information like tokens that are readily available to your socket handlers on the Elixir side is by using the `params` option above.
